
title: Bishal Thapa - Software Developer
author: bishal thapa
generator: bishal
email: thebishalthapa@gmail.com
permalink: pretty
baseurl: "" # the subpath of your site, e.g. /blogs
url: "https://thapabishal.github.io/" # the base hostname & protocol for your site
twitter_username: thebishalthapa
github_username:  thebishalthapa
# Build settings

permalink: /categories/:categories/:title

root: /
collections:
  category:
    output: true


defaults:
  -
    scope:
      path: ""
      type: categories
    values:
      layout: "categories"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

